Use conda packages instead of pip packages in test_narwhals & remove xpassing test_series_setitem from pandas tests (#21862)
It appears some narwhals jobs are failing as pip installing duckdb leads to building the project from source: https://github.com/rapidsai/cudf/actions/runs/23306081854/job/67785159324

```
× Failed to build installable wheels for some pyproject.toml based projects
╰─> duckdb
critical libmamba pip failed to install packages
```

We pinned duckdb<1.4 which do not have wheels for Python 3.14 leading to a build from source.

* Discussed offline, it's not necessary for us to test duckdb, ibis or sqlframe tests in narwhals so just removing them as dependencies all together.
* `pytest-env` is a necessary test dependency of narwhals, but this PR marks it as an available conda dependency since the testing environment is created via conda

closes https://github.com/rapidsai/cudf/issues/19983


-------

This test appears to be consistently xpassing now e.g. https://github.com/rapidsai/cudf/actions/runs/23272874292/job/67671914479?pr=21807

```bash

FAILED tests/copy_view/test_chained_assignment_deprecation.py::test_series_setitem[0] - [XPASS(strict)] Fails with cudf.pandas enabled.
FAILED tests/copy_view/test_chained_assignment_deprecation.py::test_series_setitem[indexer1] - [XPASS(strict)] Fails with cudf.pandas enabled.
FAILED tests/copy_view/test_chained_assignment_deprecation.py::test_series_setitem[indexer2] - [XPASS(strict)] Fails with cudf.pandas enabled.
FAILED tests/copy_view/test_chained_assignment_deprecation.py::test_series_setitem[indexer3] - [XPASS(strict)] Fails with cudf.pandas enabled.

```

Authors:
  - Matthew Roeschke (https://github.com/mroeschke)

Approvers:
  - Bradley Dice (https://github.com/bdice)
  - Matthew Murray (https://github.com/Matt711)

URL: https://github.com/rapidsai/cudf/pull/21862