Fix pandas failures in fillna tests (#21830)
## Description
This PR fixes 8 pytest that are failing due to the following error in
`pandas-3.0`:
```
pyarrow.lib.ArrowNotImplementedError: Unsupported cast from fixed_size_binary[8] to decimal64 using function cast_decimal64
```

## Checklist
- [x] I am familiar with the [Contributing
Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.