Raise `NotImplementedError` for `LazyFrame.profile` with the streaming exeuctor (#19257)
This raises a `NotImplementedError` in `LazyFrame.profile()` when the streaming executor is active. Previously we raised a `TypeError` when trying to construct the result.

We aren't currently able to track execution in a meaningful way with the streaming executor, and so we deliberately raise a `NotImplementedError` with a message directing users to nsys or Dask's profiling tools.

```
In [5]: df = pl.LazyFrame({"a": [1, 2, 3, 4]})

In [6]: df.sort("a").group_by("a").len().profile(engine=pl.GPUEngine(executor="streaming"))
Traceback (most recent call last):
  Cell In[6], line 1
    df.sort("a").group_by("a").len().profile(engine=pl.GPUEngine(executor="streaming"))
  File /raid/toaugspurger/envs/rapidsai/cudf/25.08/lib/python3.12/site-packages/polars/lazyframe/opt_flags.py:330 in wrapper
    return function(*args, **kwargs)
  File /raid/toaugspurger/envs/rapidsai/cudf/25.08/lib/python3.12/site-packages/polars/lazyframe/frame.py:2021 in profile
    df, timings = ldf.profile(callback)
  File /raid/toaugspurger/envs/rapidsai/cudf/25.08/lib/python3.12/site-packages/polars/_utils/scan.py:27 in _execute_from_rust
    return function(with_columns, *args)
  File ~/gh/rapidsai/cudf/python/cudf_polars/cudf_polars/callback.py:251 in _callback
    raise NotImplementedError(msg)
NotImplementedError: profile() is not supported with the streaming executor.

To profile execution with the streaming executor and 'synchronous' scheduler,
use NVIDIA NSight Systems.

To profile execution with the streaming executor and 'distributed' scheduler,
use Dask's built-in profiling tools.
```

Closes https://github.com/rapidsai/cudf/issues/19253.

Authors:
  - Tom Augspurger (https://github.com/TomAugspurger)

Approvers:
  - Matthew Murray (https://github.com/Matt711)

URL: https://github.com/rapidsai/cudf/pull/19257