Fix usage of dask-cuda in pip constraints (#23516)
Pip does not allow constraints to have extras. `depends_on_dask_cuda` previously had extras depending on the CUDA version, and as a result, the constraint file contained `dask-cuda[cu12]`. As a result, we saw the following error:

```
DEPRECATION: Constraints are only allowed to take the form of a package name and a version specifier. Other forms were originally permitted as an accident of the implementation, but were undocumented. The new implementation of the resolver no longer supports these forms. A possible replacement is replacing the constraint with a requirement. Discussion can be found at https://github.com/pypa/pip/issues/8210
ERROR: Constraints cannot have extras
```

Remove the extras in the constraints and allow the other dependencies to install the CUDA libraries instead.

This bug happened at least partly as a result of https://github.com/rapidsai/cudf/pull/21671.

Context:
https://github.com/rapidsai/cudf/actions/runs/30818064363/job/91710572211?pr=23472#step:13:86
https://github.com/rapidsai/cudf/actions/runs/30671159887/job/91293198335#step:13:95

Authors:
  - Kyle Edwards (https://github.com/KyleFromNVIDIA)

Approvers:
  - James Lamb (https://github.com/jameslamb)

URL: https://github.com/rapidsai/cudf/pull/23516