Pin pydantic<2.12 in ci/test_cudf_polars_polars_tests.sh (#20200)
pydantic made a release today, and pyiceberg was relying on [non-documented](https://docs.pydantic.dev/latest/api/pydantic_core_schema/#pydantic_core.core_schema.ValidationInfo) functionality that was removed

```python
AttributeError: 'pydantic_core._pydantic_core.ValidationInfo' object has no attribute 'current_schema_id'
```

So I think it's sufficient just to pin pydantic in our cudf_polars polars test job

Authors:
  - Matthew Roeschke (https://github.com/mroeschke)

Approvers:
  - Vyas Ramasubramani (https://github.com/vyasr)

URL: https://github.com/rapidsai/cudf/pull/20200