Workaround to enable running PDS-H via WebHDFS (#20132)
This PR provides an internal, somewhat hacky solution to facilitate general remote source testing in libcudf. By specifying two new environment variables `LIBCUDF_IO_REROUTE_LOCAL_DIR_PATTERN` and `LIBCUDF_IO_REROUTE_REMOTE_DIR_PATTERN`, at runtime libcurl will pattern match and modify any given file path (e.g. path to a local file), and instantiate an appropriate data source according to the new file path (e.g. URL to a remote file).

This PR requires a copy of local data with identical directory tree to the remote data.  This approach works for cudf-polars, and potentially (testing in progress) for Velox cudf as well. 

This PR is necessary to cudf-polars, because for HTTP-based remote files, Polars performs additional checks involving sending a HEAD request to the server, but WebHDFS does not accept HEAD requests, causing PDS-H to error out as below:

>OSError: object-store error: Generic HTTP error: Error performing HEAD http://localhost:9870/webhdfs/v1/home/tialiu/scale-100.0/supplier.parquet in 507.238µs - Server returned non-2xx status code: 400 Bad Request:

Authors:
  - Tianyu Liu (https://github.com/kingcrimsontianyu)

Approvers:
  - Lawrence Mitchell (https://github.com/wence-)
  - Matthew Murray (https://github.com/Matt711)

URL: https://github.com/rapidsai/cudf/pull/20132