Pin upper bound of numba-cuda to <0.28.0 (#21628)
* numba-cuda 0.28 no longer aliased some numba warnings causing our Python warning filters to fail https://github.com/NVIDIA/numba-cuda/issues/822
* Additionally, it appears UDFs with cudf objects are now failing compilation e.g.
```python
  File "/opt/conda/envs/test/lib/python3.12/site-packages/cudf/core/udf/utils.py", line 208, in compile_udf
    ptx_code, return_type = cuda.compile_ptx_for_current_device(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/compiler.py", line 1330, in compile_ptx_for_current_device
    return compile_ptx(
           ^^^^^^^^^^^^
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/compiler.py", line 1297, in compile_ptx
    return compile(
           ^^^^^^^^
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/core/compiler_lock.py", line 74, in _acquire_compile_lock
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/compiler.py", line 1214, in compile
    lib, resty = _compile_pyfunc_with_fixup(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/compiler.py", line 1106, in _compile_pyfunc_with_fixup
    cres = compile_cuda(
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/core/compiler_lock.py", line 74, in _acquire_compile_lock
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/compiler.py", line 789, in compile_cuda
    cres = compile_extra(
           ^^^^^^^^^^^^^^
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/compiler.py", line 599, in compile_extra
    return pipeline.compile_extra(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/core/compiler.py", line 146, in compile_extra
    return self._compile_bytecode()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/core/compiler.py", line 214, in _compile_bytecode
    return self._compile_core()
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/core/compiler.py", line 193, in _compile_core
    raise e
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/core/compiler.py", line 182, in _compile_core
    pm.run(self.state)
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/core/compiler_machinery.py", line 398, in run
    raise patched_exception
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/core/compiler_machinery.py", line 385, in run
    self._runPass(idx, pass_inst, state)
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/core/compiler_lock.py", line 74, in _acquire_compile_lock
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/core/compiler_machinery.py", line 337, in _runPass
    mutated |= check(pss.run_pass, internal_state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/core/compiler_machinery.py", line 291, in check
    mangled = func(compiler_state)
              ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/core/typed_passes.py", line 141, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
                                            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/core/typed_passes.py", line 120, in type_inference_stage
    errs = infer.propagate(raise_errors=raise_errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/test/lib/python3.12/site-packages/numba_cuda/numba/cuda/core/typeinfer.py", line 1156, in propagate
    raise errors[0]
numba.cuda.core.errors.TypingError: Failed in cuda mode pipeline (step: nopython frontend)
Unknown attribute 'Series' of type Module(<module 'cudf' from '/opt/conda/envs/test/lib/python3.12/site-packages/cudf/__init__.py'>)

File "tests/groupby/test_apply.py", line 683:
    def gdf_func(df):
        return cudf.Series([df["a"].sum(), df["b"].min(), df["c"].max()])
        ^

During: typing of get attribute at /__w/cudf/cudf/python/cudf/cudf/tests/groupby/test_apply.py (683)

File "tests/groupby/test_apply.py", line 683:
    def gdf_func(df):
        return cudf.Series([df["a"].sum(), df["b"].min(), df["c"].max()])
        ^

During: Pass nopython_type_inference

```

Authors:
  - Matthew Roeschke (https://github.com/mroeschke)
  - Matthew Murray (https://github.com/Matt711)

Approvers:
  - Vyas Ramasubramani (https://github.com/vyasr)
  - GALI PREM SAGAR (https://github.com/galipremsagar)

URL: https://github.com/rapidsai/cudf/pull/21628