Pin `deltalake` in cudf-polars-polars-tests CI job (#20255)
https://github.com/rapidsai/cudf/actions/runs/18488298392 failed with

```
_internal.DeltaError: Kernel error: Error interacting with object store...
```

on one of the polars tests. A recent update to deltalake seems to be causing that to error now.

I'm tracking that investigation in https://github.com/pola-rs/polars/issues/24872, but we can add the pin here for now.

Authors:
  - Tom Augspurger (https://github.com/TomAugspurger)

Approvers:
  - Matthew Murray (https://github.com/Matt711)
  - Bradley Dice (https://github.com/bdice)

URL: https://github.com/rapidsai/cudf/pull/20255