Ensure RAPIDS_ARTIFACTS_DIR is set for build metrics reports. (#18192)
This fixes an issue where local reproductions of CI fail with the following error:

```
 ╭─ Finding outputs from recipe
 │ Loading variant config file: "/cudf/conda/recipes/libcudf/conda_build_config.yaml"
 │
 ╰─────────────────── (took 0 seconds)
Error:   × Failed to parse recipe

Error:
  × failed to render Jinja expression: invalid operation: Environment variable RAPIDS_ARTIFACTS_DIR not found (in <string>:1)
    ╭─[conda/recipes/libcudf/recipe.yaml:45:31]
 44 │         PARALLEL_LEVEL: ${{ env.get("PARALLEL_LEVEL") }}
 45 │         RAPIDS_ARTIFACTS_DIR: ${{ env.get("RAPIDS_ARTIFACTS_DIR") }}
    ·                               ───────────────────┬──────────────────
    ·                                                  ╰── invalid operation: Environment variable RAPIDS_ARTIFACTS_DIR not found
 46 │         SCCACHE_BUCKET: ${{ env.get("SCCACHE_BUCKET") }}
    ╰────
```

Authors:
  - Bradley Dice (https://github.com/bdice)

Approvers:
  - Mike Sarahan (https://github.com/msarahan)

URL: https://github.com/rapidsai/cudf/pull/18192