Fix compile error in `binaryop/compiled/util.cpp` (#10209)
This PR fixes a compile error in `binaryop/compiled/util.cpp`, when a function with return type `std::optional` return `{}` instead of `std::nullopt`. As such, nvcc 11.5/g++-10.3 yell:
```
../src/binaryop/compiled/util.cpp: In function 'std::optional<cudf::data_type> cudf::binops::compiled::get_common_type(cudf::data_type, cudf::data_type, cudf::data_type)':
../src/binaryop/compiled/util.cpp:48:15: error: '<anonymous>' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   48 |       return {};
      |               ^
```

Authors:
  - Nghia Truong (https://github.com/ttnghia)

Approvers:
  - Robert Maynard (https://github.com/robertmaynard)
  - Karthikeyan (https://github.com/karthikeyann)
  - MithunR (https://github.com/mythrocks)
  - Bradley Dice (https://github.com/bdice)

URL: https://github.com/rapidsai/cudf/pull/10209