Add missing APIs to documentation. (#10643)
This adds a bunch of missing methods to the documentation and removes methods that no longer exist.

When building, Sphinx issues warnings like this one, which indicates that a method isn't documented:
```
.../cudf/docs/cudf/source/api_docs/api/cudf.Series.pct_change.rst: WARNING: document isn't included in any toctree
```
and this one, which indicates that a documented method no longer exists:
```
WARNING: [autosummary] failed to import cudf.Series.ceil.
Possible hints:
* ModuleNotFoundError: No module named 'cudf.Series'
* AttributeError: type object 'Series' has no attribute 'ceil'
* ImportError:
```

This PR doesn't fix all of the warnings/errors, but it is a good chunk of them.

Authors:
  - Bradley Dice (https://github.com/bdice)

Approvers:
  - GALI PREM SAGAR (https://github.com/galipremsagar)

URL: https://github.com/rapidsai/cudf/pull/10643