[BUG] Fixed a bug in the 10min notebook (#21400)
We’re seeing an issue with the cudf [10min.ipynb](https://github.com/rapidsai/cudf/blob/release/26.02/docs/cudf/source/user_guide/10min.ipynb) notebook in the 26.02 release. Running
`jupyter run 10min.ipynb` reports the following problem: 
```
NameError: name 'null' is not definedTraceback (most recent call last):
  File "/usr/local/bin/jupyter-run", line 6, in <module>
    sys.exit(RunApp.launch_instance())
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/jupyter_core/application.py", line 284, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/usr/local/lib/python3.12/dist-packages/jupyter_client/runapp.py", line 100, in start
    raise Exception(msg)
Exception: jupyter-run error running '10min.ipynb'
```
In the meantime, we don't see any issues when running the same notebook from the 25.12 release. 
In the fix, the line #444 is used exactly as it was presented in the 25.12 release.

Authors:
  - Andrei Ivanov (https://github.com/drivanov)

Approvers:
  - Matthew Roeschke (https://github.com/mroeschke)

URL: https://github.com/rapidsai/cudf/pull/21400