Make sure all dask-cudf supported aggs are handled in `_tree_node_agg` (#9487)
I noticed that for some of dask-cudf's supported aggregations (specifically `first` and `last`), we end up throwing a `ValueError` in `_tree_node_agg` because  we do not have a case for them:

```python
import cudf
import dask_cudf
from dask_sql import Context

df = cudf.DataFrame({"yr": [0, 2, 3] * 500, "inches": list(range(1500))})
ddf = dask_cudf.from_cudf(df, npartitions=5)

ddf.groupby(by="yr").agg({'yr': ['first']}).compute()
```

<details>

```
ValueError                                Traceback (most recent call last)
<ipython-input-1-7d2fee978fba> in <module>
      6 ddf = dask_cudf.from_cudf(df, npartitions=5)
      7 
----> 8 ddf.groupby(by="yr").agg({'yr': ['first']}).compute()

~/compose/etc/conda/cuda_11.2/envs/rapids/lib/python3.8/site-packages/dask/base.py in compute(self, **kwargs)
    286         dask.base.compute
    287         """
--> 288         (result,) = compute(self, traverse=False, **kwargs)
    289         return result
    290 

~/compose/etc/conda/cuda_11.2/envs/rapids/lib/python3.8/site-packages/dask/base.py in compute(*args, **kwargs)
    568         postcomputes.append(x.__dask_postcompute__())
    569 
--> 570     results = schedule(dsk, keys, **kwargs)
    571     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    572 

~/compose/etc/conda/cuda_11.2/envs/rapids/lib/python3.8/site-packages/dask/local.py in get_sync(dsk, keys, **kwargs)
    561     """
    562     kwargs.pop("num_workers", None)  # if num_workers present, remove it
--> 563     return get_async(
    564         synchronous_executor.submit,
    565         synchronous_executor._max_workers,

~/compose/etc/conda/cuda_11.2/envs/rapids/lib/python3.8/site-packages/dask/local.py in get_async(submit, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, chunksize, **kwargs)
    504             while state["waiting"] or state["ready"] or state["running"]:
    505                 fire_tasks(chunksize)
--> 506                 for key, res_info, failed in queue_get(queue).result():
    507                     if failed:
    508                         exc, tb = loads(res_info)

~/compose/etc/conda/cuda_11.2/envs/rapids/lib/python3.8/concurrent/futures/_base.py in result(self, timeout)
    435                     raise CancelledError()
    436                 elif self._state == FINISHED:
--> 437                     return self.__get_result()
    438 
    439                 self._condition.wait(timeout)

~/compose/etc/conda/cuda_11.2/envs/rapids/lib/python3.8/concurrent/futures/_base.py in __get_result(self)
    387         if self._exception:
    388             try:
--> 389                 raise self._exception
    390             finally:
    391                 # Break a reference cycle with the exception in self._exception

~/compose/etc/conda/cuda_11.2/envs/rapids/lib/python3.8/site-packages/dask/local.py in submit(self, fn, *args, **kwargs)
    546         fut = Future()
    547         try:
--> 548             fut.set_result(fn(*args, **kwargs))
    549         except BaseException as e:
    550             fut.set_exception(e)

~/compose/etc/conda/cuda_11.2/envs/rapids/lib/python3.8/site-packages/dask/local.py in batch_execute_tasks(it)
    235     Batch computing of multiple tasks with `execute_task`
    236     """
--> 237     return [execute_task(*a) for a in it]
    238 
    239 

~/compose/etc/conda/cuda_11.2/envs/rapids/lib/python3.8/site-packages/dask/local.py in <listcomp>(.0)
    235     Batch computing of multiple tasks with `execute_task`
    236     """
--> 237     return [execute_task(*a) for a in it]
    238 
    239 

~/compose/etc/conda/cuda_11.2/envs/rapids/lib/python3.8/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    226         failed = False
    227     except BaseException as e:
--> 228         result = pack_exception(e, dumps)
    229         failed = True
    230     return key, result, failed

~/compose/etc/conda/cuda_11.2/envs/rapids/lib/python3.8/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    221     try:
    222         task, data = loads(task_info)
--> 223         result = _execute_task(task, data)
    224         id = get_id()
    225         result = dumps((result, id))

~/compose/etc/conda/cuda_11.2/envs/rapids/lib/python3.8/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

~/cudf/python/dask_cudf/dask_cudf/groupby.py in _tree_node_agg(dfs, gb_cols, split_out, dropna, sort, sep)
    482             agg_dict[col] = [agg]
    483         else:
--> 484             raise ValueError(f"Unexpected aggregation: {agg}")
    485 
    486     gb = df.groupby(gb_cols, dropna=dropna, as_index=False, sort=sort).agg(

ValueError: Unexpected aggregation: first
```

</details>

This PR unifies all references to `_supported` to now reference module level `SUPPORTED_AGGS`, and makes sure all aggs in this variable are handled in `_tree_node_agg`. This variable is also imported and used in `test_groupby_basic_aggs`, so that we don't need to remember to add an agg to that test manually.

Additionally added `CudfDataFrameGroupBy.collect` to get these updated tests passing.

Authors:
  - Charles Blackmon-Luca (https://github.com/charlesbluca)

Approvers:
  - GALI PREM SAGAR (https://github.com/galipremsagar)
  - Richard (Rick) Zamora (https://github.com/rjzamora)

URL: https://github.com/rapidsai/cudf/pull/9487