Fix cudf-polars-polars-tests in nightly build
https://github.com/rapidsai/cudf/actions/runs/18488298392 failed with

```
_internal.DeltaError: Kernel error: Error interacting with object
store...
```

on one of the polars tests. A recent update to deltalake seems to be
causing that to error now.

I'm tracking that investigation in
https://github.com/pola-rs/polars/issues/24872, but we can add the pin
here for now.